#!/usr/bin/env bash

_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
_compose_args=(-f "$_script_dir/docker/compose.yml")

if [[ -f "$_script_dir/docker/compose.local.yml" ]]; then
  _compose_args+=(-f "$_script_dir/docker/compose.local.yml")
fi

docker compose "${_compose_args[@]}" build

