services:
  nasautomation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nas-automation
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      TZ: Europe/Vienna
    ports:
      - "4800:3000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
      - ../logs:/app/logs
    dns:
      - 192.168.15.122
      - 192.168.15.1
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nasautomation.rule=Host(`nasautomation.home.smallfamilybusiness.net`)"
    #   - "traefik.http.routers.nasautomation.entrypoints=https"
    #   - "traefik.http.routers.nasautomation.tls.certresolver=letsencrypt"
    #   - "traefik.http.routers.nasautomation.middlewares=authelia@file"
    #   - "traefik.http.services.nasautomation.loadbalancer.server.port=3000"
    #   - "traefik.docker.network=traefik_network"
    # networks:
    #   - traefik_network

# networks:
#   traefik_network:
#     external: true
