#!/bin/sh
set -eu

if [ -f /app/.env ]; then
  set -a
  . /app/.env
  set +a
fi

export NUXT_PLEX_HOST="${NUXT_PLEX_HOST:-${PLEX_HOST:-}}"
export NUXT_PLEX_TOKEN="${NUXT_PLEX_TOKEN:-${PLEX_TOKEN:-}}"
export NUXT_PLEX_INDEX_DIR="${NUXT_PLEX_INDEX_DIR:-${PLEX_INDEX_DIR:-}}"
export NUXT_NAS_IP="${NUXT_NAS_IP:-${NAS_IP:-}}"
export NUXT_NAS_SSH_USER="${NUXT_NAS_SSH_USER:-${NAS_SSH_USER:-}}"
export NUXT_NAS_SSH_PASS="${NUXT_NAS_SSH_PASS:-${NAS_SSH_PASS:-}}"
export NUXT_NAS_SSH_PORT="${NUXT_NAS_SSH_PORT:-${NAS_SSH_PORT:-}}"
export NUXT_NAS_SHELLY_IP="${NUXT_NAS_SHELLY_IP:-${NAS_SHELLY_IP:-}}"
export NUXT_NAS_SHELLY_RELAY="${NUXT_NAS_SHELLY_RELAY:-${NAS_SHELLY_RELAY:-}}"
export NUXT_VUPLUS_SHELLY_IP="${NUXT_VUPLUS_SHELLY_IP:-${VUPLUS_SHELLY_IP:-}}"
export NUXT_VUPLUS_SHELLY_RELAY="${NUXT_VUPLUS_SHELLY_RELAY:-${VUPLUS_SHELLY_RELAY:-}}"
export NUXT_PROXMOX_HOST="${NUXT_PROXMOX_HOST:-${PROXMOX_HOST:-}}"
export NUXT_PROXMOX_NODE="${NUXT_PROXMOX_NODE:-${PROXMOX_NODE:-}}"
export NUXT_PROXMOX_TOKEN_ID="${NUXT_PROXMOX_TOKEN_ID:-${PROXMOX_TOKEN_ID:-}}"
export NUXT_PROXMOX_TOKEN_SECRET="${NUXT_PROXMOX_TOKEN_SECRET:-${PROXMOX_TOKEN_SECRET:-}}"
export NUXT_PBS_TOKEN_ID="${NUXT_PBS_TOKEN_ID:-${PBS_TOKEN_ID:-}}"
export NUXT_PBS_TOKEN_SECRET="${NUXT_PBS_TOKEN_SECRET:-${PBS_TOKEN_SECRET:-}}"
export NUXT_PBS_HOST="${NUXT_PBS_HOST:-${PBS_HOST:-}}"
export NUXT_PUBLIC_VUPLUS_IP="${NUXT_PUBLIC_VUPLUS_IP:-${VUPLUS_IP:-}}"
export NUXT_PUBLIC_ORF1="${NUXT_PUBLIC_ORF1:-${ORF1:-}}"

exec script -q -a -c "node ./.output/server/index.mjs" /app/logs/app.log
